[package]
name = "dbus-oxidized"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
doc-comment = "0.3.3"
zbus = "3.12.0"
zvariant = "3.12.0"
